name: RocketPlaceholders
author: Lorenzo0111
main: me.lorenzo0111.rocketplaceholders.RocketPlaceholders
version: @version@
api-version: "1.13"
softdepend:
  - Vault
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - JShader
description: Create custom placeholders with PlaceholderAPI
folia-supported: true
commands:
  rocketplaceholders:
    description: RocketPlaceholders main command!
    aliases: [rp, placeholders]
permissions:
  rocketplaceholders.command:
    description: Use rocketplaceholders main command
  rocketplaceholders.command.debug:
    description: Use the debug subcommand
  rocketplaceholders.command.info:
    description: Use the info subcommand
  rocketplaceholders.command.list:
    description: Use the list subcommand
  rocketplaceholders.command.reload:
    description: Use the reload subcommand
  rocketplaceholders.command.test:
    description: Use the test subcommand