name: RocketPlaceholders
author: Lorenzo0111
main: me.Lorenzo0111.RocketPlaceholders.RocketPlaceholders
version: 1.5
softdepend: [PlaceholderAPI]
description: Create custom placeholders with PlaceholderAPI
commands:
  rocketplaceholders:
    description: RocketPlaceholders main command!
    aliases: [rp, placeholders]
permissions:
  rocketplaceholders.command:
    description: Placeholders command